# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
        language: system
  - repo: local
    hooks:
      - id: dprint
        name: dprint
        entry: dprint fmt --incremental=false --allow-no-files
        language: node
        pass_filenames: false
        additional_dependencies: [dprint]
      - id: check-added-large-files
        name: Check for added large files
        stages: [pre-commit]
        entry: check-added-large-files
        language: system
      - id: ruff_format
        name: Ruff format
        stages: [pre-commit]
        language: system
        entry: uv run ruff format
        types: [python]
      - id: ruff_lint
        name: Ruff lint
        stages: [pre-commit]
        language: system
        entry: uv run ruff check --fix
        types: [python]
      - id: xdoctest
        name: xdoctest
        stages: [pre-commit]
        language: system
        entry: rye run xdoctest
        types: [python]
      - id: pydocstringformatter
        name: pydocstringformatter
        stages: [pre-commit]
        language: system
        entry: rye run pydocstringformatter src tests
        types: [python]
      - id: mypy
        name: mypy
        stages: [pre-commit]
        language: system
        entry: rye run mypy
        types: [python]
        require_serial: true
      - id: pydoclint
        name: pydoclint
        stages: [pre-commit]
        language: system
        entry: rye run pydoclint
        types: [python]
        require_serial: true
      - id: pytest
        name: pytest
        stages: [pre-commit]
        language: system
        entry: rye run pytest tests
        types: [python]
        pass_filenames: false
