"""Configuration file for `ensemble_run_analysis`."""

import pathlib
from typing import Literal

HOME = pathlib.Path().home()
DATA_DIR_ROOT = (
    pathlib.Path("/media") / "een023" / "LaCie" / "een023" / "cesm" / "model-runs"
)

# Means are found by calculating the mean of the control runs:
## TREFHT = era.pre_made.control_trefht()[0].mean()
MEANS: dict[Literal["TREFHT", "AEROD_v"], float] = {
    "TREFHT": 287.37903283,
    "AEROD_v": 0.11947094220873525,
}
DATA_ATTRS = [
    "TREFHT850forcing-control",
    "TREFHTB1850C5CN",
    "TREFHT-full",
    "FSNTOA-full",
    "AODVISstdn",
    "LWCF-full",
    "FLUT-full",
    "SWCF-full",
    "AODDUST",
    "ICEFRAC",
    "AEROD_v",
    "FSNTOA",
    "AODVIS",
    "TREFHT",
    "so4_a1",
    "so4_a2",
    "so4_a3",
    "TROP_P",
    "TMSO2",
    "FLUT",
    "FLNT",
    "FSNT",
    "FLNS",
    "LWCF",
    "SWCF",
    "FUL",
    "FDL",
    "FUS",
    "FDS",
    "SO2",
    "SST",
    "T",
    "U",
]
DATA_ATTRS_EXTRA = {
    "TREFHT850forcing-control": ["Reference height temperature", "K"],
    "TREFHTB1850C5CN": ["Reference height temperature", "K"],
    "TREFHT-full": ["Reference height temperature", "K"],
    "FSNTOA-full": ["Net solar flux at top of atmosphere", "W/m2"],
    "AODVISstdn": ["Stratospheric aerosol optical depth 550 nm day night", "1"],
    "LWCF-full": ["Longwave cloud forcing", "W/m2"],
    "FLUT-full": ["Upwelling longwave flux at top of model", "W/m2"],
    "SWCF-full": ["Shortwave cloud forcing", "W/m2"],
    "AODDUST": ["Aerosol optical depth 550 nm from dust day only", "1"],
    "ICEFRAC": ["Fraction of surface area covered by sea-ice", "fraction"],
    "AEROD_v": ["Total Aerosol Optical Depth in visible band", "1"],
    "FSNTOA": ["Net solar flux at top of atmosphere", "W/m2"],
    "AODVIS": ["Aerosol optical depth 550 nm day only", "1"],
    "TREFHT": ["Reference height temperature", "K"],
    "so4_a1": ["so4_a1 concentration", "kg/kg"],
    "so4_a2": ["so4_a2 concentration", "kg/kg"],
    "so4_a3": ["so4_a3 concentration", "kg/kg"],
    "TROP_P": ["Tropopause Pressure", "Pa"],
    "TMSO2": ["SO2 burden", "Tg"],
    "FLUT": ["Upwelling longwave flux at top of model", "W/m2"],
    "FLNT": ["Net longwave flux at top of model", "W/m2"],
    "FSNT": ["Net solar flux at top of model", "W/m2"],
    "FLNS": ["Net longwave flux at surface", "W/m2"],
    "LWCF": ["Longwave cloud forcing", "W/m2"],
    "SWCF": ["Shortwave cloud forcing", "W/m2"],
    "FUL": ["Longwave upward flux", "W/m2"],
    "FDL": ["Longwave downward flux", "W/m2"],
    "FUS": ["Shortwave upward flux", "W/m2"],
    "FDS": ["Shortwave downward flux", "W/m2"],
    "SO2": ["SO2 concentration", "mol/mol"],
    "SST": ["sea surface temperature", "K"],
    "T": ["Temperature", "K"],
    "U": ["Zonal wind", "m/s"],
}

POINTS_DICTS: dict[
    Literal[
        "circle",
        "point",
        "pixel",
        "triangle_down",
        "triangle_up",
        "triangle_left",
        "triangle_right",
        "tri_down",
        "tri_up",
        "tri_left",
        "tri_right",
        "octagon",
        "square",
        "pentagon",
        "plus (filled)",
        "star",
        "hexagon1",
        "hexagon2",
        "plus",
        "x",
        "x (filled)",
        "diamond",
        "thin_diamond",
        "vline",
        "hline",
        "tickleft",
        "tickright",
        "tickup",
        "tickdown",
        "caretleft",
        "caretright",
        "caretup",
        "caretdown",
        "caretleft (centered at base)",
        "caretright (centered at base)",
        "caretup (centered at base)",
        "caretdown (centered at base)",
    ],
    str | int,
] = {
    "point": ".",
    "pixel": ",",
    "circle": "o",
    "triangle_down": "v",
    "triangle_up": "^",
    "triangle_left": "<",
    "triangle_right": ">",
    "tri_down": "1",
    "tri_up": "2",
    "tri_left": "3",
    "tri_right": "4",
    "octagon": "8",
    "square": "s",
    "pentagon": "p",
    "plus (filled)": "P",
    "star": "*",
    "hexagon1": "h",
    "hexagon2": "H",
    "plus": "+",
    "x": "x",
    "x (filled)": "X",
    "diamond": "D",
    "thin_diamond": "d",
    "vline": "|",
    "hline": "_",
    "tickleft": 0,
    "tickright": 1,
    "tickup": 2,
    "tickdown": 3,
    "caretleft": 4,
    "caretright": 5,
    "caretup": 6,
    "caretdown": 7,
    "caretleft (centered at base)": 8,
    "caretright (centered at base)": 9,
    "caretup (centered at base)": 10,
    "caretdown (centered at base)": 11,
}

FONTSIZE = 5
COLOR_DICTS: dict[Literal["accent", "category10", "dark2", "set1"], list] = {
    # Same as palettable.colorbrewer.qualitative.Accent_8.hex_colors
    "accent": [
        "#7fc97f",
        "#beaed4",
        "#fdc086",
        "#ffff99",
        "#386cb0",
        "#f0027f",
        "#bf5b17",
        "#666666",
    ],
    # Same as palettable.tableau.Tableau_10.hex_colors
    "category10": [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#7f7f7f",
        "#bcbd22",
        "#17becf",
    ],
    # Same as palettable.colorbrewer.qualitative.Dark2_8.hex_colors
    "dark2": [
        "#1b9e77",
        "#d95f02",
        "#7570b3",
        "#e7298a",
        "#66a61e",
        "#e6ab02",
        "#a6761d",
        "#666666",
    ],
    # Same as palettable.colorbrewer.qualitative.Set1_9.hex_colors
    # Also from https://colorbrewer2.org/#type=qualitative&scheme=Set1&n=9
    "set1": [
        "#e41a1c",
        "#377eb8",
        "#4daf4a",
        "#984ea3",
        "#ff7f00",
        "#ffff33",
        "#a65628",
        "#f781bf",
        "#999999",
    ],
}

# fmt: off
_C = COLOR_DICTS["category10"]
_P = POINTS_DICTS
_DATA_TYPES = Literal[
    "P", "P100", "VT", "c2w", "c2wm", "c2wmp", "ob16",
    "c2ws", "c2wn", "greg", "t10", "m20", "m20*"
]
LEGENDS: dict[_DATA_TYPES, dict] = {
    "P": {"c": _C[4], "marker": _P["star"], "s": 15, "zorder": 5, "label": "P"},
    "P100": {"c": _C[6], "marker": _P["square"], "s": 5, "zorder": 5, "label": "J05"},
    "VT": {"c": _C[8], "marker": _P["plus"], "s": 15, "zorder": 5, "label": "T"},
    "c2w": {"c": _C[0], "marker": _P["diamond"], "ms": 2, "zorder": 4, "label": "C2W"},
    "c2wm": {"c": _C[0], "marker": _P["triangle_down"], "s": 5, "zorder": 3, "label": r"C2W$\downarrow$"},
    "c2wmp": {"c": _C[1], "marker": _P["diamond"], "s": 5, "zorder": 3, "label": r"C2W$-$"},
    "c2ws": {"c": _C[2], "marker": _P["triangle_up"], "s": 5, "zorder": 3, "label": r"C2W$\uparrow$"},
    "c2wn": {"c": _C[5], "marker": _P["tri_up"], "s": 15, "zorder": 4, "label": r"C2WN$\uparrow$"},
    "greg": {"c": _C[7], "marker": _P["x"], "s": 5, "zorder": -1, "label": "G16"},
    "t10": {"c": _C[6], "marker": _P["circle"], "s": 5, "zorder": 5, "label": "T10"},
    "m20": {"c": _C[3], "marker": _P["thin_diamond"], "s": 5, "zorder": 2, "label": "M20"},
    "m20*": {"c": _C[3], "marker": _P["thin_diamond"], "ms": 2, "zorder": 2, "label": "M20"},
    "ob16": {"c": _C[2], "marker": _P["triangle_down"], "ms": 2, "zorder": 2, "label": "OB16"},
}
# fmt: on
